version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Skipper1267489052
      MYSQL_USER: vitdien
      MYSQL_PASSWORD: Skipper1267489052
      MYSQL_DATABASE: spring
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
